import type { Metadata } from "next";
import "./index.css";

import { Vazirmatn } from "next/font/google";
import React from "react";
const vazirmatnFont = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazirmatnFont.className + " dir-rtl h-screen"}>
        <div id="modal"></div>
        <div id="menu"></div>
        {children}
      </body>
    </html>
  );
}
